// 独立刷题导航站数据
// 字段：name 站点名、description 简介、url 官方链接、tags 标签短语、accent 主题色、category 分类

export const categories = [
  { id: 'all', name: '全部', accent: '#6c5ce7' },
  { id: 'learn', name: '基础学习', accent: '#0ea5e9' },
  { id: 'platform', name: '刷题平台', accent: '#22c55e' },
  { id: 'contest', name: '竞赛资源', accent: '#ff7a45' },
  { id: 'dev', name: '软件开发', accent: '#8b5cf6' },
]

export const ojs = [
  // === 基础学习（知识网站、课程、教学） ========================================
  {
    slug: 'oi-wiki',
    name: 'OI Wiki',
    description: '算法竞赛经典开源学习平台，覆盖数据结构、算法、数学一整套知识体系。',
    url: 'https://oi-wiki.org/',
    tags: ['开源', '算法', '知识库'],
    category: 'learn',
    accent: '#2f6feb',
    badge: '📚 算法百科',
  },
  {
    slug: 'acwing',
    name: 'AcWing',
    description: '早期热门算法学习平台。注：近年更新迟滞，推荐结合其他平台使用。',
    url: 'https://www.acwing.com/',
    tags: ['算法课', '题单', '早期热门'],
    category: 'learn',
    accent: '#1abc9c',
    badge: '⚠️ 更新迟滞',
  },
  {
    slug: 'nowcoder-study',
    name: '牛客知识体系',
    description: '牛客网学习中心，从 0 到 1 构建算法与编程知识体系，适合系统化入门。',
    url: 'https://www.nowcoder.com/problem/tracker',
    tags: ['知识体系', '入门', '教程'],
    category: 'learn',
    accent: '#4ec5b1',
    badge: '🌱 从 0 到 1',
  },
  {
    slug: 'jisuanke',
    name: '计蒜客',
    description: '程序设计学习与竞赛平台，适合初学者打基础。',
    url: 'https://www.jisuanke.com/',
    tags: ['新手', '基础', '训练'],
    category: 'learn',
    accent: '#16a085',
    badge: '🌱 入门首选',
  },
  {
    slug: 'imooc',
    name: '慕课网',
    description: '国内知名程序员在线教育平台，覆盖前后端、算法、运维全方向。',
    url: 'https://www.imooc.com/',
    tags: ['在线课', '实战', '体系'],
    category: 'learn',
    accent: '#2080d0',
    badge: '🎬 视频课程',
  },
  {
    slug: 'educoder',
    name: 'Educoder',
    description: '信息技术类实践教学平台，高校实训常用，闯关式学习。',
    url: 'https://www.educoder.net/',
    tags: ['实训', '教学', '闯关'],
    category: 'learn',
    accent: '#0e7c66',
    badge: '🏫 高校实训',
  },
  {
    slug: 'w3cschool',
    name: 'W3Cschool',
    description: '编程入门与文档教程平台，题库覆盖前后端基础。',
    url: 'https://www.w3cschool.cn/',
    tags: ['教程', '文档', '入门'],
    category: 'learn',
    accent: '#43b97f',
    badge: '📝 入门文档',
  },

  // === 刷题平台（真正在线评测的 OJ） ==========================================
  {
    slug: 'codeforces',
    name: 'Codeforces',
    description: '最贴近 XCPC 方向的全球算法竞赛平台，适合正式训练与每周比赛。',
    url: 'https://codeforces.com/',
    tags: ['Div.1/2', 'Rating', 'XCPC'],
    category: 'platform',
    accent: '#3b6cb0',
    badge: '🏆 XCPC 主战场',
  },
  {
    slug: 'luogu',
    name: '洛谷',
    description: '国内 OI 信息学竞赛主流社区，OIer 金牌刷题站，题解活跃。',
    url: 'https://www.luogu.com.cn/',
    tags: ['OI', '金牌', '题解'],
    category: 'platform',
    accent: '#52a0e5',
    badge: '🎯 OI 金牌',
  },
  {
    slug: 'nowcoder',
    name: '牛客网',
    description: '国内互联网笔试面试一站式平台，适合新手入门刷题与校招准备。',
    url: 'https://www.nowcoder.com/',
    tags: ['校招', '笔试', '求职'],
    category: 'platform',
    accent: '#4ec5b1',
    badge: '⭐ 新手友好',
  },
  {
    slug: 'atcoder',
    name: 'AtCoder',
    description: '日本顶级算法竞赛平台，题风清新、题目质量高，ABC 适合新手。',
    url: 'https://atcoder.jp/home',
    tags: ['ABC/ARC/AGC', '高质量', '日服'],
    category: 'platform',
    accent: '#222222',
    badge: '🇯🇵 思维训练',
  },
  {
    slug: 'qoj',
    name: 'QOJ',
    description: '国内大花（出题人）建立的题目信息分享平台，可查询比赛与讨论。',
    url: 'https://qoj.ac/',
    tags: ['出题人', '比赛', '讨论'],
    category: 'platform',
    accent: '#e056fd',
    badge: '🌸 大花出品',
  },
  {
    slug: 'leetcode',
    name: '力扣 LeetCode',
    description: '面向求职面试场景的刷题平台，中英双站，企业真题题库海量。',
    url: 'https://leetcode.cn/',
    tags: ['面试', '大厂真题', '中文'],
    category: 'platform',
    accent: '#f0a000',
    badge: '🔥 面试必备',
  },
  {
    slug: 'hdu',
    name: '杭电 HDU OJ',
    description: '杭州电子科技大学在线评测系统，老牌 ACM 训练平台。',
    url: 'https://acm.hdu.edu.cn/',
    tags: ['ACM', '经典题库', '中文'],
    category: 'platform',
    accent: '#c0392b',
    badge: '📚 老牌 OJ',
  },
  {
    slug: 'poj',
    name: '北大 POJ',
    description: '北京大学在线评测系统，国内最早一批 OJ，题目经典。',
    url: 'http://poj.org/',
    tags: ['ACM', '经典', '入门'],
    category: 'platform',
    accent: '#8e44ad',
    badge: '🎓 学术经典',
  },

  // === 竞赛资源（榜单查询、赛讯、选手信息） ===================================
  {
    slug: 'xcpc-io',
    name: 'XCPC.io',
    description: 'XCPC 指南与榜单查询，覆盖赛事信息、训练资源、往年赛卷。',
    url: 'https://xcpc.io/zh/guide/',
    tags: ['XCPC', '榜单', '指南'],
    category: 'contest',
    accent: '#ff6b35',
    badge: '📊 榜单指南',
  },
  {
    slug: 'acmer-info',
    name: 'ACMer.info',
    description: '致力于服务算法竞赛选手的导航站，整合训练资源与赛事入口。',
    url: 'https://acmer.info/',
    tags: ['导航', '选手', '资源'],
    category: 'contest',
    accent: '#0f9b6c',
    badge: '🧭 选手导航',
  },
  {
    slug: 'quantiji',
    name: '圈子题 QuanTiJi',
    description: '可查询题目来源所涉及的其他 OJ 比赛题目，便于跨平台找原题。',
    url: 'https://quantiji.ac/',
    tags: ['题目来源', '跨平台', '查询'],
    category: 'contest',
    accent: '#7c3aed',
    badge: '🔎 跨 OJ 溯源',
  },
  {
    slug: 'algowiki',
    name: 'AlgoWiki',
    description: '竞赛常用信息查询平台，支持近期比赛、网赛日程与提醒。',
    url: 'https://www.algowiki.cn/',
    tags: ['赛事提醒', '网赛', '日程'],
    category: 'contest',
    accent: '#0891b2',
    badge: '⏱️ 赛讯',
  },
  {
    slug: 'cpcfinder',
    name: 'CPCFinder',
    description: 'XCPC 学校与选手信息查询平台，附带战绩统计。',
    url: 'https://cpcfinder.com/',
    tags: ['XCPC', '学校', '选手'],
    category: 'contest',
    accent: '#dc2626',
    badge: '🏫 学校战绩',
  },
  {
    slug: 'lankao',
    name: '蓝桥杯信息查询',
    description: '基于 GitHub Pages 的蓝桥杯学校与选手信息查询小工具。',
    url: 'https://c16nh22o4.github.io/',
    tags: ['蓝桥杯', '选手', '信息'],
    category: 'contest',
    accent: '#2563eb',
    badge: '🏆 蓝桥杯',
  },

  // === 软件开发（程序员通用） ==================================================
  {
    slug: 'github',
    name: 'GitHub',
    description: '全球最大代码托管与协作平台，程序员必备，汇集开源生态。',
    url: 'https://github.com/',
    tags: ['代码托管', '开源', '协作'],
    category: 'dev',
    accent: '#24292e',
    badge: '💻 必备',
  },
  {
    slug: 'juejin',
    name: '掘金',
    description: '国内技术社区与高质量文章平台，程序员信息交流首选。',
    url: 'https://juejin.cn/',
    tags: ['技术社区', '文章', '资讯'],
    category: 'dev',
    accent: '#1e80ff',
    badge: '✍️ 技术社区',
  },
  {
    slug: 'kaggle',
    name: 'Kaggle',
    description: '全球领先数据科学社区，提供数据集、竞赛、教程与云端算力。',
    url: 'https://www.kaggle.com/',
    tags: ['数据科学', '竞赛', '教程'],
    category: 'dev',
    accent: '#20beff',
    badge: '📊 数据科学',
  },
]

export const stats = {
  ojs: ojs.length,
  learn: 0,
  platform: 0,
  contest: 0,
  dev: 0,
}

for (const oj of ojs) {
  if (stats[oj.category] !== undefined) stats[oj.category] += 1
}
